### PR TITLE
Schema Documentation

### PR DESCRIPTION
**Pull request by TylerMetz**
## Describe your changes
Added image of current schema and image of future changes to SQL database.

## Issue ticket number and link
#438

### CODE REVIEW

**Review by samforstot — APPROVED** [review]
So this is our current schema, we'll talk about more in our meeting but I'm curious to hear how we can improve. Looks a lot less daunting than how I imagined.

**Review by rileycleavenger — COMMENTED** [review]
What is the RecipeData table? Also where are the tables for List data?

**Comment by TylerMetz** [comment]
> What is the RecipeData table? Also where is the table for List data (UsersLists)?

After getting back on the horse today, these were the tables I saw in the .db file. Will be happy to clear up and gaps in knowledge and the Sprint 7 2 Planning meeting.

**Comment by rileycleavenger** [comment]
> > What is the RecipeData table? Also where is the table for List data (UsersLists)?
> 
> After getting back on the horse today, these were the tables I saw in the .db file. Will be happy to clear up and gaps in knowledge and the Sprint 7 2 Planning meeting.

Ok ya, so RecipeData is only in old versions of the .db file, it isn't used in the program anymore. Also UserLists prob wasn't in there bc you hadn't added anything to your list, but I'll fill you in more during the meeting.

**Review by rileycleavenger — APPROVED** [review]
V2 looks good! I'm excited to see this finished

**Pull request merged**
