### PR TITLE
Added our new logos

### PR DESCRIPTION
**Pull request by samforstot**
## Describe your changes
Made it so that our logos appear when we are on the login page and on the task bar at the top! 
## Issue ticket number and link
#409

### CODE REVIEW

**Comment by rileycleavenger** [comment]
LGTM! We just need to remember to switch it to the home page once we have that done

**Review by rileycleavenger — APPROVED** [review]
So fire

**Comment by steeleelliott03** [comment]
LGTM. Just loaded on my end and looks fresh.

**Review by steeleelliott03 — APPROVED** [review]
Fire. Realized i didn't submit on vs code.

**Pull request merged**
